# A test file for the configuration parser.


profiles: # This config test provides all available fields.
  - profile_name: "Profile1"
    pipeline:
      - operation: "crop"
        crop_config:
          width: 100
          height: 200
          alignment: "center"
      - operation: "resize"
        resize_config:
          algorithm: "catmullrom"
          width: 100
          height: 200
          factor: 0.9
      - operation: "icc_embed"
        icc_config:
          icc_name: "sRGB"
      - operation: "encode"
        encode_config:
          format: "jpeg"
          options:
            quality: 80
      - operation: "write"
        write_config:
          format: "jpeg"
          suffix: "_suffix1"
          prefix: "prefix1_"

